# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Radio Dzimbabwe
email: fran.garikayi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analysing Zimbabwe's economy and society from a Marxist-Leninist perspective
baseurl: ""
url: "https://valentinegarikayi.github.io/podcasts"
twitter_username: veegarikayi
github_username:  valentine.garikayi

permalink: /:year/:title.html


# Build settings
markdown: kramdown
