# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zim Left Radio (ZLR)
email: fran.garikayi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analysing Zimbabwe's economy and society from a Marxist-Leninist perspective
lang: en-uk
author: Valentine Garikayi
baseurl: "/podcasts"
url: "https://valentinegarikayi.github.io"
twitter_username: veegarikayi
github_username:  valentine.garikayi
permalink: /:title.html
excerpt_separator: <!--more-->

timezone: United Kingdom

# Build settings
markdown: kramdown

collections:
  transcripts:
    output: true
    permalink: /transcripts/:name/
